name: API Continous Testing 

on:
  # push:
  # branches:
  #    - main
  # pull_request:
  # schedule:
  #  - cron: '0 0 * * *' # Run daily at midnight UTC
  workflow_dispatch:
    inputs:
      run-tests:
        description: 'Manually trigger the tests'
        required: true
        default: 'true'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ${{ github.workspace }}

    - name: Run tests
      run: pytest -v tests/test_users.py
      working-directory: ${{ github.workspace }}
